//  = [
//   "Dasha Shreemali Jain Murti Pujak Samaj",
//   "Kankrej Pragati Samaj",
//   "Shree Bangalore Brahmkshatriya Samaj (Regd)",
//   "Shri Ahir Samaj Bangalore",
//   "Shri Bangalore Bhatia Samaj",
//   "Shri Bangalore Ghoghari Visa Shreemali Jain Sangh",
//   "Shri Bangalore Gujarati Brahm Samaj",
//   "Shri Bangalore Kadhayata Samaj",
//   "Shri Bangalore Kapol Samaj",
//   "Shri Bangalore Lohana Samaj",
//   "Shri Bangalore Patidar Samaj (Peenya)",
//   "Shri Bangalore Sagar Samaj",
//   "Shri Dasa Shrimali Jain Murthi poojak Samaj",
//   "Shri Dasa Shrimali Vaishno Vanik Gyanti",
//   "Shri Dasa Sorathia Vanik Gyanti",
//   "Shri Devanahalli Patidar Samaj",
//   "Shri Gujrati Vardhaman Sthanakvashi Jain Sangha",
//   "Shri Gurjar Kashtriya Kadiya Samaj",
//   "Shri Halari Visa Oswal Samaj",
//   "Shri Kadava Patidar Samaj (KR Puram)",
//   "Shri Kadva Patidar Samaj (Doddabellapur)",
//   "Shri Katch Kaduva Patidar Sanatan Samaj (Yelhanka)",
//   "Shri Katchi Gurjar Jain Pariwar",
//   "Shri Kutch Vaghad Leva Patidar Samaj",
//   "Shri Kutchi Dasa Oswal Jain Gnati Mahajan Bangalore",
//   "Shri Kutchi Visa Oswal Jain Samaj",
//   "Shri Lakshminarayan Patidar Samaj (Nalmangala)",
//   "Shri Lalbhag Patidar Samaj",
//   "Shri Matchhukantha Jain Mandal",
//   "Shri Modh Bandhu Samaj",
//   "Shri Patidar Parivar Samaj",
//   "Shri Samast Leva Patel Samaj",
//   "Shri Satwara Samaj Bangalore",
//   "Shri Saurashtra Uma Parivar Bangalore",
//   "Shri Shrimali Soni Samaj",
//   "Shri Umiya Patidar Sanatan Samaj",
//   "Shri Uttar Gujrati Patidar Samaj",
//   "Shri Vansh Suthar Samaj Bangalore",
//   "Shri Vishwakarma Gujarati Samaj",
//   "Sri Umiya Patidar Samaj (Indiranagar)",
//   "Others"
// ];
